name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - json
  - matplotlib.pyplot
  - datetime
  - ipywidgets
  - uk_covid19
  - voila
